// Per-project payment settings. GENERATED by scripts/scaffold.mjs from product.json.
// The values below are defaults; the scaffold overwrites this file per product.
export const CREATIVE_MODE: 'none' | 'download' | 'video' = 'none';
export const PAYMENT_METHODS: Array<'applePay' | 'googlePay' | 'card'> = ['applePay', 'googlePay', 'card'];
export const REQUIRE_CONSENT = true;
export const WALLET_REQUIRE_CONSENT = false;
export const CHECK_CONSENT_BY_DEFAULT = true;
export const LOCALE = 'en';
// Require ?d_country to be present for non-comp (mirrors the xracademy /xhosp gate). Set false for
// the download-template behavior (non-comp without d_country).
export const REQUIRE_COUNTRY = true;
