#!/usr/bin/env node
// ~/.claude/hooks/self-improve.mjs
// Stop hook. After each session ends, scan the session transcript for
// friction events (denied tool calls, repeated prompts on the same
// command, hook denials) and propose allow / hook additions that
// would have prevented them.
//
// Output: appends one block per session to
// ~/.claude/projects/-Users-sabiridwan-Projects-zyncai/memory/project_autonomy_self_improve.md
// (or creates it). Idempotent. Stays under 4 KiB per session entry
// to keep the memory file bounded.

import { readFileSync, writeFileSync, existsSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const HOME = homedir();
const MEMORY_FILE = join(
  HOME,
  '.claude',
  'projects',
  '-Users-sabiridwan-Projects-zyncai',
  'memory',
  'project_autonomy_self_improve.md',
);
const MAX_PER_SESSION_BYTES = 4096;

async function readStdin() {
  return new Promise((resolve, reject) => {
    let buf = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (c) => (buf += c));
    process.stdin.on('end', () => resolve(buf));
    process.stdin.on('error', reject);
  });
}

function nowIso() {
  return new Date().toISOString().replace(/\.\d+Z$/, 'Z');
}

function classifyFriction(event) {
  // Returns a one-line suggestion if this event signals friction, else null.
  const tool = event.tool || event.tool_name || '';
  const cmd = event.command || event.tool_input?.command || '';
  const path = event.file_path || event.tool_input?.file_path || '';

  // Hook denied a Bash command -> suggest a wider allowlist entry
  if (event.hook_decision === 'deny' && tool === 'Bash' && cmd) {
    const trimmed = cmd.replace(/\s+/g, ' ').slice(0, 80);
    return `add to ALLOW in bash-ambiguity-classifier.mjs: \`${trimmed}\``;
  }
  // User declined the prompt twice (same command) -> suggest permission rule
  if (event.user_declined_count && event.user_declined_count >= 2 && cmd) {
    return `add Bash(${cmd.split(' ')[0]}*) to permissions.allow in settings.json`;
  }
  // Edit/Write prompt on a safe path -> path missing from edit-classifier
  if (event.permission_decision === 'ask' && (tool === 'Edit' || tool === 'Write') && path) {
    if (path.startsWith('/Users/sabiridwan/') && !path.startsWith('/Users/sabiridwan/.claude/')) {
      return `add path root to edit-classifier.mjs SAFE_PREFIXES: ${path.split('/').slice(0, 5).join('/')}/`;
    }
  }
  return null;
}

(async () => {
  // Stop hook payload: { session_id, transcript_path, cwd, reason }
  let payload;
  try {
    payload = JSON.parse((await readStdin()) || '{}');
  } catch {
    process.exit(0);
  }

  const sessionId = payload.session_id || 'unknown';
  const cwd = payload.cwd || '';

  // Skip non-zyncai sessions — self-improve is project-scoped
  if (!cwd.includes('/Users/sabiridwan/Projects/zyncai')) {
    process.exit(0);
  }

  const transcriptPath = payload.transcript_path;
  if (!transcriptPath || !existsSync(transcriptPath)) {
    process.exit(0);
  }

  // Parse transcript for friction events. Transcript is JSONL.
  let transcript;
  try {
    transcript = readFileSync(transcriptPath, 'utf8');
  } catch {
    process.exit(0);
  }

  const lines = transcript.split('\n').filter(Boolean);
  const suggestions = new Set();
  let eventsScanned = 0;
  for (const line of lines) {
    let entry;
    try {
      entry = JSON.parse(line);
    } catch {
      continue;
    }
    if (!entry || typeof entry !== 'object') continue;
    eventsScanned++;
    const sug = classifyFriction(entry);
    if (sug) suggestions.add(sug);
  }

  if (suggestions.size === 0) {
    process.exit(0);
  }

  const block = [
    ``,
    `## ${nowIso()} session=${sessionId.slice(0, 8)}`,
    `cwd: ${cwd}`,
    `scanned ${eventsScanned} transcript events`,
    ``,
    `Friction surfaced:`,
    ...[...suggestions].slice(0, 20).map((s) => `- ${s}`),
    ``,
  ].join('\n');

  const trimmed = block.length > MAX_PER_SESSION_BYTES ? block.slice(0, MAX_PER_SESSION_BYTES) + '\n[...truncated]\n' : block;

  if (!existsSync(MEMORY_FILE)) {
    const header = [
      `---`,
      `name: zyncai-autonomy-self-improve`,
      `description: Auto-generated suggestions from self-improve.mjs Stop hook. Each session appends friction events + proposed allow / hook additions.`,
      `metadata:`,
      `  type: project`,
      `---`,
      ``,
      `# Autonomy self-improve log`,
      ``,
      `Each entry below was generated by ~/.claude/hooks/self-improve.mjs at session stop. Skim before next planning session; promote any suggestion into an actual allow / hook edit.`,
      ``,
    ].join('\n');
    writeFileSync(MEMORY_FILE, header + trimmed, 'utf8');
  } else {
    appendFileSync(MEMORY_FILE, trimmed, 'utf8');
  }

  process.exit(0);
})();
